apiVersion: v1
kind: Pod
metadata: 
  name: ali-a100
spec:
  tolerations:
  - key: nautilus.io/mizzou-vigir
    operator: Exists
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - gpn-fiona-mizzou-2.rnet.missouri.edu
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-A100-SXM4-80GB
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  - name: data
    persistentVolumeClaim:
      claimName: ali-vol-100g
  containers:
  - name: gpu-container
    # image: gitlab-registry.nrp-nautilus.io/smatous/ai_city_ali:more_path
    image: gitlab-registry.nrp-nautilus.io/smatous/dem2so_large_dataset_2
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: 32Gi
        cpu: 16
        nvidia.com/gpu: 1
      requests:
        memory: 32Gi
        cpu: 16
        nvidia.com/gpu: 1
    volumeMounts:
      - name: dshm
        mountPath: /dev/shm
      - name: data
        mountPath: /root/home/test_data