apiVersion: batch/v1
kind: Job
metadata: 
  name: cvpr-traffic-${model}-${split}
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A10
                - NVIDIA-A6000
                  #- NVIDIA-GeForce-RTX-3090
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/smatous/ollama_datasets:cars_air_traf
        command: ["/bin/bash", "-c"]
        args: ["cd /root/home/; pip install transformers; git clone https://github.com/SMATousi/ViGIR_CVPR_LLM.git; export WANDB_API_KEY=5f0550a5efaee6dacd932e9d1178f33022ed081b; cd ViGIR_CVPR_LLM/prompting_framework/; ollama serve & sleep 10; python run_traffic_CLIP_debugged.py --model_name ${model} --prompt 'Your task is to identify this traffic sign from the class list. Your answer MUST be less than 77 characters.' --subset ${split}"] 
        resources:
          limits:
            memory: 4Gi
            cpu: 4
            nvidia.com/gpu: 1
            ephemeral-storage: "1000G"
          requests:
            memory: 4Gi
            cpu: 4
            nvidia.com/gpu: 1
            ephemeral-storage: "1000G"
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      restartPolicy: Never
