apiVersion: v1
kind: Pod
metadata: 
    name: ali-pod-gpu-a10-test4
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090
            - NVIDIA-A10
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/smatous/dem2so_large_dataset_2
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: 32Gi
        cpu: 16
        nvidia.com/gpu: 2
        ephemeral-storage: "1000G"
      requests:
        memory: 32Gi
        cpu: 16
        nvidia.com/gpu: 2
        ephemeral-storage: "1000G"
    volumeMounts:
      - name: dshm
        mountPath: /dev/shm