apiVersion: v1
kind: Pod
metadata: 
    name: ali-pod-gpu-3090-test-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/smatous/rgbdem2so
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: 32Gi
        cpu: 16
        nvidia.com/gpu: 1
      requests:
        memory: 32Gi
        cpu: 16
        nvidia.com/gpu: 1