apiVersion: batch/v1
kind: Job
metadata: 
  name: ali-job-dem2so-4gpus-batch8-test-3
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-3090
                - NVIDIA-GeForce-RTX-2080-Ti
                - NVIDIA-TITAN-RTX
                - NVIDIA-RTX-A5000
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/smatous/dem2so_large_dataset_2
        command: ["/bin/bash", "-c"]
        args: ["cd /root/home/data; pip install accelerate; tar -xvzf Archive.tar.gz; cd ..; git clone https://github.com/SMATousi/dem2so.git; cd dem2so; export WANDB_API_KEY=5f0550a5efaee6dacd932e9d1178f33022ed081b; accelerate launch train_rgb_accel.py --epochs 1000 --modelname Unet_1 --batchsize 8 --nottest --logging --projectname RGB_DEM_2_SO --runname ExDATA-4GPUs-batch32-ukn"]  
        resources:
          limits:
            memory: 64Gi
            cpu: 16
            nvidia.com/gpu: 4
          requests:
            memory: 64Gi
            cpu: 16
            nvidia.com/gpu: 4
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      restartPolicy: Never