apiVersion: v1
kind: Pod
metadata: 
    name: ali-pod-gully-det-128-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            # - NVIDIA-GeForce-RTX-3090
            - NVIDIA-A10
            - NVIDIA-A6000
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/smatous/gully-detection-128
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: 32Gi
        cpu: 16
        nvidia.com/gpu: 2
      requests:
        memory: 32Gi
        cpu: 16
        nvidia.com/gpu: 2