apiVersion: batch/v1
kind: Job
metadata: 
  name: ali-job-gd-freezed-pretrained-rand-embed-05-batch64
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A10
                - NVIDIA-A6000
                # - NVIDIA-GeForce-RTX-3090
                # - NVIDIA-GeForce-RTX-2080-Ti
                # - NVIDIA-TITAN-RTX
                # - NVIDIA-RTX-A5000
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/smatous/gully_classification:224
        command: ["/bin/bash", "-c"]
        args: ["cd /root/home/data; pip install transformers; pip install rasterio; pip install gudhi; pip install accelerate; tar -xvzf Archive_224.tar; cd ..; git clone https://github.com/SMATousi/Gully_Detection.git; cd Gully_Detection/gully_detection/; export WANDB_API_KEY=5f0550a5efaee6dacd932e9d1178f33022ed081b; accelerate launch vit_train_rgb_accel_kfold.py --projectname GD_ViT --runname ViT-224-freezed-rand-embed-05-batch64 --batchsize 16 --nottest --logging --init_embed --freeze_weight"]  
        resources:
          limits:
            memory: 64Gi
            cpu: 8
            nvidia.com/gpu: 4
            ephemeral-storage: "1000G"
          requests:
            memory: 64Gi
            cpu: 8
            nvidia.com/gpu: 4
            ephemeral-storage: "1000G"
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      restartPolicy: Never