apiVersion: v1
kind: Pod
metadata: 
    name: gully-128-gpu-unet-3090-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/smatous/gully128
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: 16Gi
        cpu: 8
        nvidia.com/gpu: 1
      requests:
        memory: 16Gi
        cpu: 8
        nvidia.com/gpu: 1