apiVersion: batch/v1
kind: Job
metadata: 
  name: gully-128-gpu-unet2-2x3090-job-bcm-batch16-2
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-3090
      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/smatous/gully128
        command: ["/bin/bash", "-c"]
        args: ["cd /root/home/; git clone https://github.com/SMATousi/Unet_rgb_to_so.git; cd Unet_rgb_to_so; export WANDB_API_KEY=5f0550a5efaee6dacd932e9d1178f33022ed081b; python3 run_train_128.py --projectname Good-Gully-detection-128-Unet --runname Unet2-BCMLoss-batch-16 --modelname Unet_2 --batchsize 16 --nottest"]  
        resources:
          limits:
            memory: 16Gi
            cpu: 8
            nvidia.com/gpu: 2
          requests:
            memory: 16Gi
            cpu: 8
            nvidia.com/gpu: 2
      restartPolicy: Never