apiVersion: batch/v1
kind: Job
metadata:
  name: cpu-job-ali-iksolver-numdim-100-p2-1
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
    
      containers:
        - name: cpu-container
          image: gitlab-registry.nrp-nautilus.io/smatous/ali-pytorch-tensorflow 
          command: ["/bin/bash", "-c"]
          args: ["pip install pygad; git clone https://github.com/jacketdembys/wcci24.git; cd wcci24; cd ea-based-nn-ik-solver; export WANDB_API_KEY=5f0550a5efaee6dacd932e9d1178f33022ed081b; python3 run_ga_torch.py --projectname GA-IK --runname sol-100-gen-1000-p2 --seed --numsolutions 100 --numgeneration 1000 --numparents 2"]
          resources:
            limits:
              memory: "64G"
              cpu: "64"
            requests:
              memory: "64G"
              cpu: "64"
      restartPolicy: Never