apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ali-vol-100g
spec:
  storageClassName: rook-cephfs-central
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi