apiVersion: batch/v1
kind: Job
metadata:
  name: cpu-job-ali-raeproject-numdim-2
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
    
      containers:
        - name: cpu-container
          image: gitlab-registry.nrp-nautilus.io/smatous/ali-pytorch-tensorflow 
          command: ["/bin/bash", "-c"]
          args: ["git clone https://github.com/SMATousi/outlier_VAE; cd outlier_VAE; git checkout rae-laptop; pip install pygad; export WANDB_API_KEY=5f0550a5efaee6dacd932e9d1178f33022ed081b; python3 mag_test_script.py"]
          resources:
            limits:
              memory: "64G"
              cpu: "64"
            requests:
              memory: "64G"
              cpu: "64"
      restartPolicy: Never
