apiVersion: batch/v1
kind: Job
metadata:
  name: cpu-job-ali-raeproject-uns-30
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
    
      containers:
        - name: cpu-container
          image: gitlab-registry.nrp-nautilus.io/smatous/ali-pytorch-tensorflow 
          command: ["/bin/bash", "-c"]
          args: ["git clone https://github.com/SMATousi/outlier_VAE; cd outlier_VAE; git checkout sara-test; pip install pygad; export WANDB_API_KEY=5f0550a5efaee6dacd932e9d1178f33022ed081b; python3 cluster-scripts/script.py --projectname uns_MUSK1 --runname RAE-latent2 --latentdim 2 --modelname RAE --datasetname musk"]
          resources:
            limits:
              memory: "32G"
              cpu: "16"
            requests:
              memory: "32G"
              cpu: "16"
      restartPolicy: Never
