apiVersion: batch/v1
kind: Job
metadata: 
  name: ${job_name}
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A10
                - NVIDIA-GeForce-RTX-3090
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/smatous/unimatch_vigir:pascal
        command: ["/bin/bash", "-c"]
        args: ["cd /root/home/; git clone https://github.com/SMATousi/UnimatchV2_ViGIR.git; mv pretrained UnimatchV2_ViGIR/; export WANDB_API_KEY=5f0550a5efaee6dacd932e9d1178f33022ed081b; cd UnimatchV2_ViGIR/; sh scripts/train_arguments.sh 1 8080 ${meth}_${size} Unimatch_RAE_366_pascal_final 366 ${size} ${meth} pascal"]  
        resources:
          limits:
            memory: 8Gi
            cpu: 4
            nvidia.com/gpu: 1
            ephemeral-storage: "1000G"
          requests:
            memory: 8Gi
            cpu: 4
            nvidia.com/gpu: 1
            ephemeral-storage: "1000G"
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      restartPolicy: Never