apiVersion: apps/v1
kind: Deployment
metadata:
  name: ali-dep-test
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ali-unimatch-dep-092-1
  template:
    metadata: 
      labels:
        k8s-app: ali-unimatch-dep-092-1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                # - NVIDIA-GeForce-RTX-3090
                - NVIDIA-A10
                - NVIDIA-A6000
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: data
        persistentVolumeClaim:
          claimName: ali-vol-100g
      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/smatous/ollama_datasets:cars_air_traf
        command: ["sleep", "infinity"]
        resources:
          limits:
            memory: 4Gi
            cpu: 2
            nvidia.com/gpu: 1
          requests:
            memory: 4Gi
            cpu: 2
            nvidia.com/gpu: 1
        volumeMounts:
          - name: dshm
            mountPath: /dev/shm
          - name: data
            mountPath: /root/home/test_data
